# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/srh/Projects/Tutorials/priorityEncoder_FPGA/Arty/priorityEncoder.cache/wt [current_project]
set_property parent.project_path /home/srh/Projects/Tutorials/priorityEncoder_FPGA/Arty/priorityEncoder.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo /home/srh/Projects/Tutorials/priorityEncoder_FPGA/Arty/priorityEncoder.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/srh/Projects/Tutorials/hardwareHarness_src/pmod_oled/charLib.coe
read_verilog -library xil_defaultlib /home/srh/Projects/Tutorials/priorityEncoder_FPGA/verilog/pri_enc.v
read_vhdl -library xil_defaultlib {
  /home/srh/Projects/Tutorials/hardwareHarness_src/pmod_oled/Delay.vhd
  /home/srh/Projects/Tutorials/hardwareHarness_src/pmod_oled/OledInit.vhd
  /home/srh/Projects/Tutorials/hardwareHarness_src/pmod_oled/OledUser.vhd
  /home/srh/Projects/Tutorials/hardwareHarness_src/pmod_oled/PmodOLEDCtrl.vhd
  /home/srh/Projects/Tutorials/hardwareHarness_src/pmod_oled/SpiCtrl.vhd
  /home/srh/Projects/Tutorials/hardwareHarness_src/debounce.vhd
  /home/srh/Projects/Tutorials/hardwareHarness_src/helper_funcs.vhd
  /home/srh/Projects/Tutorials/priorityEncoder_FPGA/VHDL/priorityEncoder.vhd
  /home/srh/Projects/Tutorials/priorityEncoder_FPGA/VHDL/fpga_top.vhd
}
read_ip -quiet /home/srh/Projects/Tutorials/hardwareHarness_src/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/srh/Projects/Tutorials/hardwareHarness_src/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/srh/Projects/Tutorials/hardwareHarness_src/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/srh/Projects/Tutorials/hardwareHarness_src/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/srh/Projects/Tutorials/hardwareHarness_src/mem_oled_char_lib/mem_oled_char_lib.xci
set_property used_in_implementation false [get_files -all /home/srh/Projects/Tutorials/hardwareHarness_src/mem_oled_char_lib/mem_oled_char_lib_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/srh/Projects/Tutorials/priorityEncoder_FPGA/XDC/fpga_constraints.xdc
set_property used_in_implementation false [get_files /home/srh/Projects/Tutorials/priorityEncoder_FPGA/XDC/fpga_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top fpga_top -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_top_utilization_synth.rpt -pb fpga_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
